name: Java CI with Gradle

on:
  push:
    branches:
      - "master" # Trigger on push to the master branch
  pull_request:
    branches:
      - "master" # Trigger on pull request to the master branch

jobs:
  build:
    # Build job
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        java: [8, 11, 17] # Test against multiple Java versions

    steps:
      # Step 1: Check out the code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up the JDK
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Step 4: Set up Gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      # Step 5: Build the project with Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Step 6: Run tests
      - name: Run Tests
        run: ./gradlew test

      # Step 7: Run Static Code Analysis
      - name: Run Static Analysis
        run: ./gradlew check

  dependency-submission:
    # Dependency graph submission job
    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs: build # Runs only if the build job is successful

    steps:
      # Step 1: Check out the code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up the JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Submit dependency graph
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4.0.0
